import { state } from './state.js';
import { CLIENTS } from '../data/clients.js';
import { DOSSIERS } from '../data/dossiers.js';
import { Rules } from './rules.js';
import { applyWorkflow } from './workflow.js';
import { ROUTES, renderView } from './router.js';
import { viewDashboard } from '../views/dashboard.js';
import { viewClients } from '../views/clients.js';
import { viewDossiers } from '../views/dossiers.js';
import { viewWizard } from '../views/wizard.js';
import { visibleDossiers } from './utils.js';
import { dossierTable } from './utils.js';
import { STATUT_LABELS } from '../data/statuts.js';
import { findClient } from './utils.js';
import { REFS } from '../data/refs.js';
import { findRef } from './utils.js';
import { INDEXES } from '../data/indexes.js';
import { idx } from './utils.js';
import { EXCEPTIONS_TAUX } from '../data/exceptions-taux.js';
import { findExceptionTaux } from './utils.js';
import { dossierActionsFor } from './workflow.js';


console.log("STATE =", state);
console.log("NB CLIENTS =", CLIENTS.length);
console.log("NB DOSSIERS =", DOSSIERS.length);
console.log("RULES =", Rules);
console.log("WORKFLOW =", applyWorkflow);
console.log("ROUTES =", ROUTES);
console.log("RENDERVIEW =", renderView);
console.log("DASHBOARD =", viewDashboard);
console.log("CLIENTS VIEW =", viewClients);
console.log("DOSSIERS VIEW =", viewDossiers);
console.log("WIZARD VIEW =", viewWizard);
console.log("VISIBLE DOSSIERS =", visibleDossiers);
console.log("DOSSIER TABLE =", dossierTable);
console.log("STATUTS =", STATUT_LABELS);
console.log("FIND CLIENT =", findClient);
console.log("NB REFS =", REFS.length);
console.log("FIND REF =", findRef);
console.log("NB INDEXES =", INDEXES.length);
console.log("IDX =", idx);
console.log("NB EXCEPTIONS =", EXCEPTIONS_TAUX.length);
console.log("FIND EXCEPTION =", findExceptionTaux);
console.log("DOSSIER ACTIONS =", dossierActionsFor);
